[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  
  # Supabase
  REACT_APP_SUPABASE_URL = "${REACT_APP_SUPABASE_URL}"
  REACT_APP_SUPABASE_ANON_KEY = "${REACT_APP_SUPABASE_ANON_KEY}"
  
  # Auth
  NEXTAUTH_URL = "${URL}"
  NEXTAUTH_SECRET = "${NEXTAUTH_SECRET}"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables will be set in Netlify UI
# SUPABASE_URL
# SUPABASE_ANON_KEY
# DATABASE_URL (Neon)
# NEXT_PUBLIC_SUPABASE_URL
# NEXT_PUBLIC_SUPABASE_ANON_KEY
