services:
  - type: web
    name: annuerp-backend
    env: docker
    region: frankfurt  # or your preferred region
    plan: free
    branch: main
    dockerfilePath: backend/Dockerfile
    buildCommand: cd backend && npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://annu-erp.vercel.app  # Update this with your actual frontend URL